#!/bin/bash
echo "🚀 Quick Backend Deployment Guide"
echo "=================================="
echo ""
echo "1. Go to: https://render.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect repo: couchpotato027/room-radar"
echo "5. Settings:"
echo "   - Name: room-radar-backend"
echo "   - Root Directory: backend"
echo "   - Build: npm install && npx prisma generate"
echo "   - Start: npm start"
echo "6. Add env vars (see URGENT_FIX.md)"
echo "7. Deploy!"
echo ""
echo "Then set REACT_APP_API_URL in Vercel"
